<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Sri Lanka Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\Sprint2\Module1Home]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Module1Home]]></DName>
<Res><![CDATA[Res49]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:28]]></Time>
<TimeTick>1649171788</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:28]]></Time>
<TimeTick>1649171788</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:31]]></Time>
<TimeTick>1649171791</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:31]]></Time>
<TimeTick>1649171791</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Desktops.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:31]]></Time>
<TimeTick>1649171791</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" >
<Disp><![CDATA[Desktops.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Mac (1).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:31]]></Time>
<TimeTick>1649171791</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[Mac (1).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Desktops.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:33]]></Time>
<TimeTick>1649171793</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[Desktops.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[NavigationBar]]></Obj>
<Details ><![CDATA[NavigationBar Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:33]]></Time>
<TimeTick>1649171793</TimeTick>
<NodeArgs eType="User" icon="9" nRep="19" status="Passed" >
<Disp><![CDATA[NavigationBar]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:35]]></Time>
<TimeTick>1649171795</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:35]]></Time>
<TimeTick>1649171795</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Your Store.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:35]]></Time>
<TimeTick>1649171795</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[Your Store.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Your Store.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:36]]></Time>
<TimeTick>1649171796</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" >
<Disp><![CDATA[Your Store.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="22" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[StoreLogo]]></Obj>
<Details ><![CDATA[StoreLogo  Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:36]]></Time>
<TimeTick>1649171796</TimeTick>
<NodeArgs eType="User" icon="9" nRep="25" status="Passed" >
<Disp><![CDATA[StoreLogo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["$ Currency"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" status="Warning" >
<Disp><![CDATA["$ Currency"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["$ Currency"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=$ Currency<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=$ Currency<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>html id=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>value=$ Currency<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=btn btn-link dropdown-toggle<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" >
<Disp><![CDATA["$ Currency"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[$ Currency.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" >
<Disp><![CDATA[$ Currency.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[£ Pound Sterling.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:46:58]]></Time>
<TimeTick>1649171818</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" >
<Disp><![CDATA[£ Pound Sterling.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["$ Currency"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:01]]></Time>
<TimeTick>1649171821</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="88" status="Warning" >
<Disp><![CDATA["$ Currency"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["$ Currency"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=submit<br>name=$ Currency<br>micclass=WebButton<br>html tag=BUTTON<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (19 objects found)&nbsp;</FONT></u><br>
micclass=WebButton<br>html tag=BUTTON<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=$ Currency<SPAN class=Failed> (Skipped)</SPAN><br>type=submit<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>html id=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>value=$ Currency<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>class=btn btn-link dropdown-toggle<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:01]]></Time>
<TimeTick>1649171821</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="89" >
<Disp><![CDATA["$ Currency"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[$ Currency.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:01]]></Time>
<TimeTick>1649171821</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="90" >
<Disp><![CDATA[$ Currency.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" status="Warning" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" status="Warning" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[CurrencyBlock]]></Obj>
<Details ><![CDATA[CurrencyBlock Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:01]]></Time>
<TimeTick>1649171821</TimeTick>
<NodeArgs eType="User" icon="9" nRep="91" status="Passed" >
<Disp><![CDATA[CurrencyBlock]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:03]]></Time>
<TimeTick>1649171823</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:03]]></Time>
<TimeTick>1649171823</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Shopping Cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:03]]></Time>
<TimeTick>1649171823</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="95" >
<Disp><![CDATA[Shopping Cart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Shopping Cart.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" >
<Disp><![CDATA[Shopping Cart.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="94" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="93" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[ShoppingCart]]></Obj>
<Details ><![CDATA[ShoppingCart Unavailable]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<NodeArgs eType="User" icon="9" nRep="99" status="Failed" >
<Disp><![CDATA[ShoppingCart]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[0 item(s) - £0.00.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="103" >
<Disp><![CDATA[0 item(s) - £0.00.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[0 item(s) - £0.00.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="104" >
<Disp><![CDATA[0 item(s) - £0.00.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="102" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="101" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[CartButton]]></Obj>
<Details ><![CDATA[CartButton Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:04]]></Time>
<TimeTick>1649171824</TimeTick>
<NodeArgs eType="User" icon="9" nRep="105" status="Passed" >
<Disp><![CDATA[CartButton]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:07]]></Time>
<TimeTick>1649171827</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:07]]></Time>
<TimeTick>1649171827</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Wish List (0).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:07]]></Time>
<TimeTick>1649171827</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="109" >
<Disp><![CDATA[Wish List (0).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Wish List (0).Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:08]]></Time>
<TimeTick>1649171828</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="110" >
<Disp><![CDATA[Wish List (0).Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="108" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="107" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[WishlistDisplay]]></Obj>
<Details ><![CDATA[WishlistDisplay Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:08]]></Time>
<TimeTick>1649171828</TimeTick>
<NodeArgs eType="User" icon="9" nRep="111" status="Passed" >
<Disp><![CDATA[WishlistDisplay]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:10]]></Time>
<TimeTick>1649171830</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:10]]></Time>
<TimeTick>1649171830</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:10]]></Time>
<TimeTick>1649171830</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[My Account.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:10]]></Time>
<TimeTick>1649171830</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="116" >
<Disp><![CDATA[My Account.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="114" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="113" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[MyAccount]]></Obj>
<Details ><![CDATA[MyAccount  Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:10]]></Time>
<TimeTick>1649171830</TimeTick>
<NodeArgs eType="User" icon="9" nRep="117" status="Passed" >
<Disp><![CDATA[MyAccount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:11]]></Time>
<TimeTick>1649171831</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:11]]></Time>
<TimeTick>1649171831</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:11]]></Time>
<TimeTick>1649171831</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="121" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[My Account.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:11]]></Time>
<TimeTick>1649171831</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="122" >
<Disp><![CDATA[My Account.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="120" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="119" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[MyAccount]]></Obj>
<Details ><![CDATA[MyAccount  Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:12]]></Time>
<TimeTick>1649171832</TimeTick>
<NodeArgs eType="User" icon="9" nRep="123" status="Passed" >
<Disp><![CDATA[MyAccount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:12]]></Time>
<TimeTick>1649171832</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:12]]></Time>
<TimeTick>1649171832</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Register.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:12]]></Time>
<TimeTick>1649171832</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="127" Source="Action1" SourceLine="63" >
<Disp><![CDATA[Register.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="129" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[My Account.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="130" >
<Disp><![CDATA[My Account.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="126" Source="Action1" SourceLine="63" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="125" Source="Action1" SourceLine="63" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[MyAccount]]></Obj>
<Details ><![CDATA[MyAccount  Available]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<NodeArgs eType="User" icon="9" nRep="131" status="Passed" >
<Disp><![CDATA[MyAccount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 20:47:14]]></Time>
<TimeTick>1649171834</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="135" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="134" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="133" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/5/2022 - 20:46:22" eTime="4/5/2022 - 20:47:16" passed="9" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T62">
<AName><![CDATA[Action2]]></AName>
<Summary sTime="4/5/2022 - 20:47:16" eTime="4/5/2022 - 20:47:16" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="137" >
<Disp><![CDATA[Action2 Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T63">
<AName><![CDATA[Action3]]></AName>
<Summary sTime="4/5/2022 - 20:47:16" eTime="4/5/2022 - 20:47:16" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="139" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Module1Home Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/5/2022 - 20:46:18" eTime="4/5/2022 - 20:47:16" passed="9" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Module1Home Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>