<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Sri Lanka Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\OpenCart_Home\Driver\Module1Home]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Module1Home]]></DName>
<Res><![CDATA[Res87]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Tr_Home]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Tr_Home" started.]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:04]]></Time>
<TimeTick>1649304724</TimeTick>
<NodeArgs eType="Transaction" icon="5" nRep="8" nType="Start Transaction" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Tr_Home]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:16]]></Time>
<TimeTick>1649304736</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:16]]></Time>
<TimeTick>1649304736</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:20]]></Time>
<TimeTick>1649304740</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:20]]></Time>
<TimeTick>1649304740</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[search_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Laptop"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:20]]></Time>
<TimeTick>1649304740</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" >
<Disp><![CDATA[search_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:21]]></Time>
<TimeTick>1649304741</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="18" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[WebButton.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:21]]></Time>
<TimeTick>1649304741</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="19" >
<Disp><![CDATA[WebButton.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="15" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[SearchBox]]></Obj>
<Details ><![CDATA[SearchBox  Available]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:21]]></Time>
<TimeTick>1649304741</TimeTick>
<NodeArgs eType="User" icon="11" nRep="20" status="Passed" >
<Disp><![CDATA[SearchBox]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:26]]></Time>
<TimeTick>1649304746</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:26]]></Time>
<TimeTick>1649304746</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[search_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mac"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:26]]></Time>
<TimeTick>1649304746</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" >
<Disp><![CDATA[search_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:26]]></Time>
<TimeTick>1649304746</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[WebButton.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:27]]></Time>
<TimeTick>1649304747</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" >
<Disp><![CDATA[WebButton.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="22" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[SearchBox]]></Obj>
<Details ><![CDATA[SearchBox  Available]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:27]]></Time>
<TimeTick>1649304747</TimeTick>
<NodeArgs eType="User" icon="11" nRep="28" status="Passed" >
<Disp><![CDATA[SearchBox]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:31]]></Time>
<TimeTick>1649304751</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:31]]></Time>
<TimeTick>1649304751</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[search_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Apple"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:31]]></Time>
<TimeTick>1649304751</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" >
<Disp><![CDATA[search_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:31]]></Time>
<TimeTick>1649304751</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[WebButton.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:32]]></Time>
<TimeTick>1649304752</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" >
<Disp><![CDATA[WebButton.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="31" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="30" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[SearchBox]]></Obj>
<Details ><![CDATA[SearchBox  Available]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:32]]></Time>
<TimeTick>1649304752</TimeTick>
<NodeArgs eType="User" icon="11" nRep="36" status="Passed" >
<Disp><![CDATA[SearchBox]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:32]]></Time>
<TimeTick>1649304752</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:32]]></Time>
<TimeTick>1649304752</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:45]]></Time>
<TimeTick>1649304765</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:45]]></Time>
<TimeTick>1649304765</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" status="Passed" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="42" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:50]]></Time>
<TimeTick>1649304770</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Wish List (0).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:50]]></Time>
<TimeTick>1649304770</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="46" >
<Disp><![CDATA[Wish List (0).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Your Store.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:51]]></Time>
<TimeTick>1649304771</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" >
<Disp><![CDATA[Your Store.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="45" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" status="Passed" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[WishlistDisplay]]></Obj>
<Details ><![CDATA[WishlistDisplay Available]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:51]]></Time>
<TimeTick>1649304771</TimeTick>
<NodeArgs eType="User" icon="11" nRep="48" status="Passed" >
<Disp><![CDATA[WishlistDisplay]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:51]]></Time>
<TimeTick>1649304771</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:51]]></Time>
<TimeTick>1649304771</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:56]]></Time>
<TimeTick>1649304776</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:56]]></Time>
<TimeTick>1649304776</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" status="Passed" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="54" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="58" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[My Account.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="59" >
<Disp><![CDATA[My Account.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="57" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" status="Passed" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[MyAccount]]></Obj>
<Details ><![CDATA[MyAccount  Available]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<NodeArgs eType="User" icon="11" nRep="60" status="Passed" >
<Disp><![CDATA[MyAccount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Your Store.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/7/2022 - 9:42:59]]></Time>
<TimeTick>1649304779</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="63" >
<Disp><![CDATA[Your Store.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Your&nbsp;Store"&nbsp;(of&nbsp;class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/7/2022 - 9:43:23]]></Time>
<TimeTick>1649304803</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Your Store<br>openurl = https://demo.opencart.com<br>opentitle = Your Store<br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Your Store<br>]]></Details>
<Time><![CDATA[4/7/2022 - 9:43:23]]></Time>
<TimeTick>1649304803</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="67" status="Warning" nType="Description" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="66" status="Failed" nType="Run Error" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/7/2022 - 9:43:23]]></Time>
<TimeTick>1649304803</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Your Store&quot; (of class Browser).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Users\sfjbs\Desktop\OpenCart_Home\FunctionLibrary\HomeLibrary.qfl<BR/>Line (18): &quot;Browser(&quot;Your Store&quot;).Page(&quot;Your Store&quot;).Link(&quot;My Account&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/7/2022 - 9:43:23]]></Time>
<TimeTick>1649304803</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="69" status="Failed" Source="C:\Users\sfjbs\Desktop\OpenCart_Home\FunctionLibrary\HomeLibrary.qfl" SourceLine="17" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/7/2022 - 9:43:31]]></Time>
<TimeTick>1649304811</TimeTick>
<NodeArgs eType="General" icon="14" nRep="70" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" status="Failed" Source="C:\Users\sfjbs\Desktop\OpenCart_Home\FunctionLibrary\HomeLibrary.qfl" SourceLine="-1" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/7/2022 - 9:42:04" eTime="4/7/2022 - 9:43:31" passed="8" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Module1Home Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/7/2022 - 9:42:00" eTime="4/7/2022 - 9:43:31" passed="8" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Module1Home Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>