<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Sri Lanka Standard Time">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="vm001"><DocLocation><![CDATA[C:\Users\sfjbs\Desktop\Sprint2\Module1Home]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Module1Home]]></DName>
<Res><![CDATA[Res10]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Your Store]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:11]]></Time>
<TimeTick>1649139551</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Phones & PDAs]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:11]]></Time>
<TimeTick>1649139551</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Checkout_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:11]]></Time>
<TimeTick>1649139551</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="70" >
<Disp><![CDATA[Checkout_3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[account.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["guest"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:13]]></Time>
<TimeTick>1649139553</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Action1" SourceLine="71" >
<Disp><![CDATA[account.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:13]]></Time>
<TimeTick>1649139553</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="72" >
<Disp><![CDATA[Continue.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[firstname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["reshma"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="Action1" SourceLine="73" >
<Disp><![CDATA[firstname.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[lastname.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["gaikwad"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="74" >
<Disp><![CDATA[lastname.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["reshma12@gmail.com"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="Action1" SourceLine="75" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[telephone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["9000000000"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="Action1" SourceLine="76" >
<Disp><![CDATA[telephone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[company.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" Source="Action1" SourceLine="77" >
<Disp><![CDATA[company.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[address_1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="Action1" SourceLine="78" >
<Disp><![CDATA[address_1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[address_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["abc"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:14]]></Time>
<TimeTick>1649139554</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" Source="Action1" SourceLine="79" >
<Disp><![CDATA[address_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[city.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nashik"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:15]]></Time>
<TimeTick>1649139555</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" Source="Action1" SourceLine="80" >
<Disp><![CDATA[city.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[postcode.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["234555"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:15]]></Time>
<TimeTick>1649139555</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" Source="Action1" SourceLine="81" >
<Disp><![CDATA[postcode.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[country_id.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Turkey"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:17]]></Time>
<TimeTick>1649139557</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="38" Source="Action1" SourceLine="83" >
<Disp><![CDATA[country_id.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[zone_id.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Aydın"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:20]]></Time>
<TimeTick>1649139560</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" Source="Action1" SourceLine="85" >
<Disp><![CDATA[zone_id.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Continue_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:20]]></Time>
<TimeTick>1649139560</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" Source="Action1" SourceLine="86" >
<Disp><![CDATA[Continue_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Continue_3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:22]]></Time>
<TimeTick>1649139562</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="Action1" SourceLine="88" >
<Disp><![CDATA[Continue_3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[agree.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:28]]></Time>
<TimeTick>1649139568</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="46" Source="Action1" SourceLine="90" >
<Disp><![CDATA[agree.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Continue_4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:31]]></Time>
<TimeTick>1649139571</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Action1" SourceLine="92" >
<Disp><![CDATA[Continue_4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Confirm Order.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:32]]></Time>
<TimeTick>1649139572</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" Source="Action1" SourceLine="93" >
<Disp><![CDATA[Confirm Order.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Continue_5.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/5/2022 - 11:49:34]]></Time>
<TimeTick>1649139574</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" Source="Action1" SourceLine="94" >
<Disp><![CDATA[Continue_5.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="70" >
<Disp><![CDATA[Phones & PDAs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="70" >
<Disp><![CDATA[Your Store]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/5/2022 - 11:49:10" eTime="4/5/2022 - 11:49:34" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="4/5/2022 - 11:49:07" eTime="4/5/2022 - 11:49:34" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test Module1Home Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>